version: '2'

services:
  ctfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - OAUTH_PROVIDER=ctftime
      - OAUTH_CALLBACK_ENDPOINT=http://ctf.wpictf.xyz/redirect
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
      - SECRET_KEY=a4J6WWq0kRxY
      - OAUTH_CLIENT_ID=1208
      - OAUTH_CLIENT_SECRET=1bcd18e4f77c71086bebe3866f88104a47947508a66e5ed70801c9373d414aae
      - DEFAULT_EMAIL=jrbacker@wpi.edu
      - VIRTUAL_HOST=ctf.wpictf.xyz
      - LETSENCRYPT_HOST=ctf.wpictf.xyz
      - LETSENCRYPT_EMAIL=csc-exec@wpi.edu
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
    networks:
        default:
        internal:

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ctfd
    networks:
      default:
      internal:

  docker-gen:
    image: jwilder/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
    - nginx-proxy
    volumes:
    - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
    - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    networks:
      default:
      internal:

  db:
    image: mariadb:10.4.12
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
    - .data/redis:/data
    networks:
        internal:

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      default:
      internal:

networks:
    default:
    internal:
        internal: true

volumes:
  vhost:
  certs:
  acme:
  html:
  conf:
